# Generated by Django 4.2.7 on 2025-11-29 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date for aggregated metrics')),
                ('hour', models.IntegerField(blank=True, help_text='Hour of day (0-23) for hourly metrics', null=True)),
                ('total_queries', models.IntegerField(default=0, help_text='Total queries generated')),
                ('successful_queries', models.IntegerField(default=0, help_text='Successfully generated queries')),
                ('failed_queries', models.IntegerField(default=0, help_text='Failed query generations')),
                ('avg_generation_time', models.FloatField(default=0.0, help_text='Average generation time')),
                ('avg_validation_time', models.FloatField(default=0.0, help_text='Average validation time')),
                ('avg_execution_time', models.FloatField(default=0.0, help_text='Average execution time')),
                ('spl_count', models.IntegerField(default=0)),
                ('kql_count', models.IntegerField(default=0)),
                ('dsl_count', models.IntegerField(default=0)),
                ('validation_success_rate', models.FloatField(default=0.0, help_text='Percentage of valid queries')),
                ('execution_success_rate', models.FloatField(default=0.0, help_text='Percentage of successful executions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-date', '-hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='QueryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Original natural language description')),
                ('query_type', models.CharField(choices=[('spl', 'Splunk SPL'), ('kql', 'Kusto Query Language'), ('dsl', 'Elasticsearch DSL')], max_length=10)),
                ('generated_query', models.TextField(help_text='Generated query')),
                ('generation_time', models.FloatField(help_text='Time taken to generate query (seconds)')),
                ('validation_time', models.FloatField(blank=True, help_text='Time taken to validate query', null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Time taken to execute query in SIEM', null=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Whether query passed validation')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors')),
                ('validation_warnings', models.JSONField(blank=True, default=list, help_text='List of validation warnings')),
                ('execution_success', models.BooleanField(blank=True, help_text='Whether query executed successfully', null=True)),
                ('result_count', models.IntegerField(blank=True, help_text='Number of results returned', null=True)),
                ('used_sample_data', models.BooleanField(default=True, help_text='Whether sample data was used')),
                ('mitre_technique_id', models.CharField(blank=True, max_length=20, null=True)),
                ('mitre_technique_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Query Metric',
                'verbose_name_plural': 'Query Metrics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_queryme_created_07e0bf_idx'), models.Index(fields=['query_type'], name='api_queryme_query_t_4e2c8c_idx'), models.Index(fields=['is_valid'], name='api_queryme_is_vali_28f274_idx')],
            },
        ),
    ]
