# Generated by Django 4.2.7 on 2025-12-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryExecutionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time_ms', models.FloatField(help_text='Query execution time in milliseconds')),
                ('result_count', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('memory_usage_mb', models.FloatField(blank=True, null=True)),
                ('cpu_usage_percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Query Execution Log',
                'verbose_name_plural': 'Query Execution Logs',
                'db_table': 'query_execution_log',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Overall satisfaction rating')),
                ('usefulness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How useful was the query?')),
                ('accuracy_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How accurate was the query?')),
                ('comments', models.TextField(blank=True)),
                ('analyst_name', models.CharField(default='anonymous', max_length=100)),
            ],
            options={
                'verbose_name': 'Query Feedback',
                'verbose_name_plural': 'Query Feedback',
                'db_table': 'query_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLibrary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(help_text='Natural language threat description')),
                ('query_type', models.CharField(choices=[('spl', 'Splunk SPL'), ('kql', 'Kusto Query Language'), ('dsl', 'Elasticsearch DSL')], max_length=10)),
                ('query', models.TextField(help_text='Generated query')),
                ('mitre_technique_id', models.CharField(blank=True, max_length=20, null=True)),
                ('mitre_technique_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('optimization_suggestions', models.JSONField(blank=True, default=list)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('is_template', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Query Library',
                'db_table': 'query_library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('query_type', models.CharField(choices=[('spl', 'Splunk SPL'), ('kql', 'Kusto Query Language'), ('dsl', 'Elasticsearch DSL')], max_length=10)),
                ('template', models.TextField(help_text='Query template with placeholders')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('mitre_technique_id', models.CharField(blank=True, max_length=20, null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Template parameters with default values')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Query Template',
                'verbose_name_plural': 'Query Templates',
                'db_table': 'query_template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SIEMConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('siem_type', models.CharField(choices=[('splunk', 'Splunk'), ('elasticsearch', 'Elasticsearch'), ('sentinel', 'Azure Sentinel')], max_length=20)),
                ('configuration', models.JSONField(help_text='SIEM connection configuration (encrypted in production)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(default='unknown', max_length=50)),
            ],
            options={
                'verbose_name': 'SIEM Connection',
                'verbose_name_plural': 'SIEM Connections',
                'db_table': 'siem_connection',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='QueryMetrics',
        ),
        migrations.DeleteModel(
            name='SystemMetrics',
        ),
        migrations.AddField(
            model_name='queryfeedback',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.querylibrary'),
        ),
        migrations.AddField(
            model_name='queryexecutionlog',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.querylibrary'),
        ),
        migrations.AddField(
            model_name='queryexecutionlog',
            name='siem_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.siemconnection'),
        ),
    ]
