from setuptools import setup, find_packages

setup(
    name="threat-hunting-ai",
    version="1.0.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "Django>=4.2.7",
        "djangorestframework>=3.14.0",
        "python-multipart>=0.0.7",
        "streamlit>=1.28.1",
        "requests>=2.32.3",
        "ollama>=0.5.3",
        "elasticsearch>=8.10.1",
        "splunk-sdk>=1.7.4",
        "stix2>=3.0.1",
        "taxii2-client>=2.3.0",
        "pandas>=2.1.3",
        "numpy>=1.26.4",
        "python-dotenv>=1.0.0",
        "pyyaml>=6.0.1",
        "httpx>=0.27.0",
        "plotly>=5.18.0",
    ],
    entry_points={
        'console_scripts': [
            'threat-hunter-backend=backend.manage:main',
        ],
    },
    author="Cybersecurity Student",
    author_email="student@example.com",
    description="AI-powered threat hunting query generator",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/example/threat-hunting-ai",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Security",
        "Topic :: Internet :: Log Analysis",
    ],
    python_requires=">=3.9",
)